version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: deps
          command: sudo pip install flake8
      - run:
          name: requirements
          command: pip install --user -r ./requirements.txt
      - run:
          name: lint
          command: flake8 .
      - run:
          name: test
          command: echo 'TODO tests'
  
  dockerize:
    machine: true
    steps:
     - checkout
     - run: docker build -t futsaltokyo/groundstaff:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push futsaltokyo/groundstaff:$CIRCLE_BRANCH


workflows:
  version: 2
  main-flow:
    jobs:
      - test
      # - dockerize:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: master
